EMBEDDING_MODEL = "all-MiniLM-L6-v2"
EMBEDDING_DIM = 384
THETA_SIM = 0.75
THETA_COUNT = 3
K_NEIGHBORS = 20
THETA_MERGE = 0.70
STRENGTH_GENERAL = 30 * 86400
STRENGTH_CONSTRAINT = 999999 * 86400
HEALTH_REPAIR_THRESHOLD = 40
HEALTH_PENALTY_CONFLICT = 0.3
SIMILARITY_WINDOW_MIN = 0.4
SIMILARITY_WINDOW_MAX = 0.95
COGNEE_DATASET = "hackathon_demo"

RESOLUTION_TRIGGERS = ["cleared", "healed", "no longer", "resolved", "back to normal", "fully recovered", "doctor cleared"]